export const MONTHLY_INSTALLMENT_REQUEST = '@app/MONTHLY_INSTALLMENT_REQUEST';
export const MONTHLY_INSTALLMENT_SUCCESS = '@app/MONTHLY_INSTALLMENT_SUCCESS';
export const MONTHLY_INSTALLMENT_ERROR = '@app/MONTHLY_INSTALLMENT_ERROR';
export const SET_DURATION = '@app/SET_DURATION';
export const SET_AMOUNT = '@app/SET_AMOUNT';
